global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: mysql_primary
    scrape_interval: 30s
    static_configs:
    - targets: ["mysql-reporter-arvanchallenge.apps.ir-thr-ba1.arvancaas.ir"]


